config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :readings, :devices, :locations
root 'readings#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/device.rb
class Device < ApplicationRecord
  belongs_to :location
  has_many :readings
end

app/models/location.rb
class Location < ApplicationRecord
    has_many :devices
    validates :name, presence: true
end

app/models/reading.rb
class Reading < ApplicationRecord
  belongs_to :device
  validates :temperature, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
    before_action :set_device, only: [:show, :edit, :update, :destroy]

    def index
        @devices = Device.all
    end

    def show
    end

    def edit
    end
    
    def new
        @device = Device.new
    end

    def create
        @device = Device.new(device_params)
    
        respond_to do |format|
          if @device.save
            format.html { redirect_to @device, notice: 'Device was successfully created.' }
            format.json { render :show, status: :created, device: @device }
          else
            format.html { render :new }
            format.json { render json: @device.errors, status: :unprocessable_entity }
          end
        end
      end
    
    def update
      respond_to do | format |
        if @device.update(device_params)
          format.html { redirect_to @device, notice: 'Device was successfully updated.' }
          format.json { render action: 'show', status: ok, location: @device }
        else
          format.html { render action: 'edit' }
          format.json { render json: @device.errors, status: :unprocessable_entity }
        end
      end
    end

    def destroy
      @device.destroy
      respond_to do | format |
        format.html { redirect_to devices_url }
        format.json { head :no_content }
      end
    end
    private
    # Use callbacks to share common setup or constraints between actions.
    def set_device
      @device = Device.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def device_params
      params.require(:device).permit(:id, :location_id)
    end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
    before_action :set_location, only: [:show, :edit, :update, :destroy]

    def index
        @locations = Location.all
    end

    def show
    end
    
    def new
        @location = Location.new
    end

    def edit
    end

    
    def create
        @location = Location.new(location_params)
    
        respond_to do |format|
          if @location.save
            format.html { redirect_to @location, notice: 'Location was successfully created.' }
            format.json { render :show, status: :created, location: @location }
          else
            format.html { render :new }
            format.json { render json: @location.errors, status: :unprocessable_entity }
          end
        end
      end
   
    def update
      respond_to do | format |
        if @location.update(location_params)
          format.html { redirect_to @location, notice: 'Device was successfully updated.' }
          format.json { render action: 'show', status: ok, location: @location }
        else
          format.html { render action: 'edit' }
          format.json { render json: @location.errors, status: :unprocessable_entity }
        end
      end
    end
   
      private
      # Use callbacks to share common setup or constraints between actions.
      def set_location
        @location = Location.find(params[:id])
      end
  
      # Never trust parameters from the scary internet, only allow the white list through.
      def location_params
        params.require(:location).permit(:name)
      end
end

app/controllers/readings_controller.rb
class ReadingsController < ApplicationController
    before_action :set_reading, only: [:show, :edit, :update, :destroy]

    def index
        @readings = Reading.all
    end

    def show
    end

    def new
        @reading = Reading.new
    end

    def create
        @reading = Reading.new(reading_params)

        respond_to do |format|
          if @reading.save
            format.html { redirect_to @reading, notice: 'Reading was successfully created.' }
            format.json { render :show, status: :created, reading: @reading }
          else
            format.html { render :new }
            format.json { render json: @reading.errors, status: :unprocessable_entity }
          end
        end
      end


    private
    # Use callbacks to share common setup or constraints between actions.
    def set_reading
      @reading = Reading.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reading_params
      params.require(:reading).permit(:temperature, :device_id)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/readings_helper.rb
module ReadingsHelper
end

app/views/devices/_form.html.erb
<%= form_with(model: device, local: true) do |form| %>
  <% if device.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(device.errors.count, "error") %> prohibited this device from being saved:</h2>

      <ul>
      <% device.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label 'Location ID' %>
    <%= form.text_field :location_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/devices/edit.html.erb
<h1>Edit A Location</h1>

<%= render 'form', location: @location %>

<%= link_to 'Back', devices_path %>

app/views/devices/index.html.erb
<h1>Devices</h1>

<table>
<thead>
<tr>
<th>Device ID</th>
<th>Current Device Location</th>
<th>Device Created Date</th>
</tr>
</thead>

<tbody>
<% @devices.each do |device| %>
<tr>
<td><%= device.id %></td>
<td><%= device.location.name %> (<i>Loc ID <%= device.location_id %></i>)</td>
<td><%= device.created_at %></td>
</tr>
<% end %>
</tbody>
</table>

app/views/devices/new.html.erb
<h1>Store New Device</h1>

<%= render 'form', device: @device %>

<%= link_to 'Back', devices_path %>

app/views/devices/show.html.erb
<p id="notice"><%= notice %></p>

<h2>Device <%= @device.id %></h2>

<p>Device ID: <%= @device.id %></p>
<p>Location ID: <%= @device.location_id %></p>
<p>Device Created: <%= @device.created_at %></p>

<%= link_to 'Edit', edit_device_path(@device) %> |
<%= link_to 'Device List', devices_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Temperature</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/locations/_form.html.erb
<%= form_with(model: location, local: true) do |form| %>
  <% if location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% location.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/locations/edit.html.erb
<h1>Edit A Location</h1>

<%= render 'form', location: @location %>

<%= link_to 'Back', devices_path %>

app/views/locations/index.html.erb
<h1>Locations</h1>

<table>
<thead>
<tr>
<th>Name</th>
<th>Location ID</th>
<th>Created</th>
</tr>
</thead>

<tbody>
<% @locations.each do |loc| %>
<tr>
<td><%= loc.name %></td>
<td><%= loc.id %></td>
<td><%= loc.created_at %></td>
</tr>
<% end %>
</tbody>
</table>

app/views/locations/new.html.erb
<h1>New Location</h1>

<%= render 'form', location: @location %>

<%= link_to 'Back', locations_path %>

app/views/locations/show.html.erb
<p id="notice"><%= notice %></p>

<h2><%= @location.name %></h2>

<p>Location Name: <%= @location.name %></p>
<p>Location ID: <%= @location.id %></p>
<p>Created: <%= @location.created_at %></p>

<%= link_to 'Edit', edit_location_path(@location) %> |
<%= link_to 'Locations', locations_path %>

app/views/readings/_form.html.erb
<%= form_with(model: reading, local: true) do |form| %>
  <% if reading.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reading.errors.count, "error") %> prohibited this reading from being saved:</h2>

      <ul>
      <% reading.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="field">
    <%= form.label 'Device ID' %>
    <%= form.text_field :device_id %>
  </div>
  
  <div class="field">
    <%= form.label 'Temperature Reading' %>
    <%= form.text_field :temperature %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/readings/index.html.erb
<h1>Temperature Readings</h1>

<table>
<thead>
<tr>
<th>Reading ID</th>
<th>Device Location</th>
<th>Reading</th>
<th>Created Date</th>

</tr>
</thead>

<tbody>
<% @readings.each do |reading| %>
<tr>
<td><%= reading.id %></td>
<td><%= reading.device.location.name %> (device id <%= reading.device.id %>)</td>
<td><%= reading.temperature %></td>
<td><%= reading.created_at %></td>

</tr>
<% end %>
</tbody>
</table>

app/views/readings/new.html.erb
<h1>Store New Reading</h1>

<%= render 'form', reading: @reading %>

<%= link_to 'Back', readings_path %>

app/views/readings/show.html.erb
<p id="notice"><%= notice %></p>

<h2>Reading ID <%= @reading.id %></h2>

<p>Temperature: <%= @reading.temperature %></p>
<p>Device Location: <%= @reading.device.location.name %> (Device ID <%= @reading.device_id %>)</p>
<p>Reading Created: <%= @reading.created_at %></p>

<!-- <%= link_to 'Edit', edit_reading_path(@reading) %> |-->
<%= link_to 'List All Readings', readings_path %>